// <auto-generated />
using IntegerSortWebApp.App_Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IntegerSortWebApp.Migrations
{
    [DbContext(typeof(IntegerSortDBContext))]
    partial class IntegerSortDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("IntegerSortWebApp.Models.Number", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Integer")
                        .HasColumnType("int");

                    b.Property<int>("SortID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SortID");

                    b.ToTable("Numbers");
                });

            modelBuilder.Entity("IntegerSortWebApp.Models.Sort", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("SortDirection")
                        .HasColumnType("int");

                    b.Property<long>("SortTime")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Sorts");
                });

            modelBuilder.Entity("IntegerSortWebApp.Models.Number", b =>
                {
                    b.HasOne("IntegerSortWebApp.Models.Sort", "Sort")
                        .WithMany("Numbers")
                        .HasForeignKey("SortID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sort");
                });

            modelBuilder.Entity("IntegerSortWebApp.Models.Sort", b =>
                {
                    b.Navigation("Numbers");
                });
#pragma warning restore 612, 618
        }
    }
}
